### ISSUE TITLE
Dial's rotation angle never reaches rotation limit

### ISSUE THREAD

**Issue by fellowProgrammer** [guoyingtao/Puffer#1]
This a bit of a weird problem. I set the rotation limit to 180 degrees and have the following code (very similar to what was in the example project) in my viewDidLoad method to print the angle of the dial:

```
dial.didRotate = {[weak self] angle in
            guard let self = self else { return }
        print("Angle: \(self.dial.getRotationAngle().degrees)")
        }
```

However, when I mess around with the angle, I can't seem to get the angle to 180 degrees. I have also noticed that the faster you move the dial from one point to the limit the further the last printed angle value is from the limit. For example, if I move the dial very slowly to the end limit, I can get the angle to be around -179.5 but if I move it from say, -160 to what should be -180 or 180 very quickly the last angle that is printed is -172.8. Why is this happening and how can I fix it? Let me know if you need any clarification.

**Comment by guoyingtao** [comment]
@fellowProgrammer Sorry for the pretty late reply... It was a bug. I released Puffer 1.0.3 and hope it solved this issue.
